FROM golang:latest AS build

WORKDIR /build

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm GOARM=6 go build -ldflags="-w -s" -o /build/srtm-service github.com/asmyasnikov/srtm/srtm-service

FROM arm32v6/busybox

COPY --from=build /build/srtm-service /usr/local/bin/srtm-service

ENV HTTP_PORT=80
ENV TILE_DIRECTORY=/data
ENV LRU_CACHE_SIZE=100
ENV STORE_IN_MEMORY=false

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/srtm-service"]

CMD []
