FROM golang:latest AS build

RUN CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go get -ldflags="-w -s" -o /build/srtm-service github.com/asmyasnikov/srtm/srtm-service

FROM arm64v8/busybox

COPY --from=build /go/bin/srtm-service /usr/local/bin/srtm-service

ENV HTTP_PORT=80
ENV TILE_DIRECTORY=/data
ENV LRU_CACHE_SIZE=100
ENV STORE_IN_MEMORY=false

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/srtm-service"]

CMD []
