FROM golang:latest AS build

RUN CGO_ENABLED=0 GOARCH=amd64 go get -ldflags="-w -s" github.com/asmyasnikov/srtm/srtm-service

FROM amd64/busybox

COPY --from=build /go/bin/srtm-service /usr/local/bin/srtm-service

ENV HTTP_PORT=80
ENV TILE_DIRECTORY=/data
ENV LRU_CACHE_SIZE=100
ENV STORE_IN_MEMORY=false

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/srtm-service"]

CMD []
